# This is an example .goreleaser.yml file with some sensible defaults.
# Make sure to check the documentation at https://goreleaser.com

# The lines below are called `modelines`. See `:help modeline`
# Feel free to remove those if you don't want/need to use them.
# yaml-language-server: $schema=https://goreleaser.com/static/schema.json
# vim: set ts=2 sw=2 tw=0 fo=cnqoj

version: 1

before:
  hooks:
    # You may remove this if you don't use go modules.
    - go mod tidy
    # you may remove this if you don't need go generate
    - go generate ./...

builds:
  - binary: mem
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin

archives:
  - format: tar.gz
    # this name template makes the OS and Arch compatible with the results of `uname`.
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    # use zip for windows archives
    format_overrides:
      - goos: windows
        format: zip

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

brews:
  -
    name: memphis-cli
    homepage: "https://github.com/memphisdev/memphis-cli"
    description: "Memphis.dev CLI"
   # Repository to push the generated files to.
    repository:
      # Repository owner.
      #
      # Templates: allowed
      owner: memphisdev

      # Repository name.
      #
      # Templates: allowed
      name: homebrew-memphis-cli

      # Optionally a branch can be provided.
      #
      # Default: default repository branch
      # Templates: allowed
      branch: brew 

      # Optionally a token can be provided, if it differs from the token
      # provided to GoReleaser
      # Templates: allowed
      token: "{{ .Env.GITHUB_TOKEN }}"

      # Sets up pull request creation instead of just pushing to the given branch.
      # Make sure the 'branch' property is different from base before enabling
      # it.
      #
      # Since: v1.17
      # pull_request:
        # Whether to enable it or not.
      #   enabled: true

        # Whether to open the PR as a draft or not.
        #
        # Since: v1.19
        # draft: true

        # If the pull request template has checkboxes, enabling this will
        # check all of them.
        #
        # Since: v1.20 (pro).
        # This feature is only available in GoReleaser Pro.
        # check_boxex: true

        # Base can also be another repository, in which case the owner and name
        # above will be used as HEAD, allowing cross-repository pull requests.
        #
        # Since: v1.19
        # base:
        #   owner: goreleaser
        #   name: my-repo
        #   branch: main
    commit_author:
      name: memphis
      email: team@memphis.dev
chocolateys:
  - # Your app's package name.
    # The value may not contain spaces or character that are not valid for a URL.
    # If you want a good separator for words, use '-', not  '.'.
    #
    # Default: ProjectName
    name: memphis-cli 

    # IDs of the archives to use.
    # Empty means all IDs.
    # Attention: archives must not be in the 'binary' format.
    # ids:
    #   - foo
    #   - bar

    # Your app's owner.
    # It basically means you.
    owners: memphisdev

    # The app's title.
    # A human-friendly title of the package.
    #
    # Default: ProjectName
    title: memphis-cli

    # Your app's authors (probably you).
    authors: team@memphis.dev

    # Your app's project url.
    # It is a required field.
    project_url: https://memphis.dev/

    # URL which is determined by the given Token (github,
    # gitlab or gitea).
    #
    # Default: depends on the git remote
    # Templates: allowed
    url_template: "https://github.com/memphisdev/memphis-cli/releases/download/{{ .Tag }}/{{ .ArtifactName }}"

    # App's icon.
    icon_url: "https://rawcdn.githack.com/foo/bar/efbdc760-395b-43f1-bf69-ba25c374d473/icon.png"

    # Your app's copyright details.
    copyright: 2023 Memphis.dev

    # App's license information url.
    license_url: https://github.com/memphisdev/memphis/blob/master/LICENSE

    # Your apps's require license acceptance:
    # Specify whether the client must prompt the consumer to accept the package
    # license before installing.
    require_license_acceptance: false

    # Your app's source url.
    project_source_url: https://github.com/memphisdev/memphis-cli

    # Your app's documentation url.
    docs_url: https://docs.memphis.dev

    # App's bugtracker url.
    # bug_tracker_url: https://github.com/foo/barr/issues

    # Your app's tag list.
    # tags: "foo bar baz"

    # Your app's summary:
    summary: Memphis.dev CLI.

    # This the description of your chocolatey package.
    # Supports markdown.
    description: |
      {{ .ProjectName }} installer package.

    # Your app's release notes.
    # A description of the changes made in this release of the package.
    # Supports markdown. To prevent the need to continually update this field,
    # providing a URL to an external list of Release Notes is perfectly
    # acceptable.
    release_notes: "https://docs.memphis.dev/memphis/release-notes/releases"

    # App's dependencies
    # The version is not required.
    # dependencies:
    #  - id: nfpm
    #    version: 2.20.0

    # The api key that should be used to push to the chocolatey repository.
    #
    # WARNING: do not expose your api key in the configuration file!
    api_key: "{{ .Env.CHOCOLATEY_API_KEY }}"

    # The source repository that will push the package to.
    source_repo: "https://push.chocolatey.org/"

    # Setting this will prevent goreleaser to actually try to push the package
    # to chocolatey repository, leaving the responsibility of publishing it to
    # the user.
    skip_publish: true

    # GOAMD64 to specify which amd64 version to use if there are multiple
    # versions from the build section.
    #
    # Default: 'v1'
    goamd64: v1
