# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class MemphisCli < Formula
  desc ""
  homepage "https://github.com/memphisdev/memphis-cli"
  version "0.0.1"

  on_macos do
    if Hardware::CPU.arm?
      url "https://github.com/memphisdev/memphis-cli/releases/download/v0.0.1/memphis-cli_Darwin_arm64.tar.gz"
      sha256 "8803a2d0dcc5b35c000c9bfc5e169a53cf1fcec537e0757dfe0b2c32b9a83b2c"

      def install
        bin.install "mem"
      end
    end
    if Hardware::CPU.intel?
      url "https://github.com/memphisdev/memphis-cli/releases/download/v0.0.1/memphis-cli_Darwin_x86_64.tar.gz"
      sha256 "87aaa148bad06054f02786a7b103bba341309c2302d588fa8ce4439d5c27eace"

      def install
        bin.install "mem"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel?
      url "https://github.com/memphisdev/memphis-cli/releases/download/v0.0.1/memphis-cli_Linux_x86_64.tar.gz"
      sha256 "8f60028ec9840fa669ab2714f1686ced2631055c9dcbae73dc7b375971a8978d"

      def install
        bin.install "mem"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/memphisdev/memphis-cli/releases/download/v0.0.1/memphis-cli_Linux_arm64.tar.gz"
      sha256 "d30a780780b0ed609516ea48abb38115ef8fd21f3bb706da9664baecc8a0bfdd"

      def install
        bin.install "mem"
      end
    end
  end
end
